// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRF3CHZ11M6hec1T0Jcs_JO8zpI9z3dIY',
    appId: '1:261848373856:web:9b13b81e9180eef895c105',
    messagingSenderId: '261848373856',
    projectId: 'raceapp-d75e0',
    authDomain: 'raceapp-d75e0.firebaseapp.com',
    databaseURL: 'https://raceapp-d75e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raceapp-d75e0.firebasestorage.app',
    measurementId: 'G-BZPVQYZDDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDijmbFjRgdO6TMYnNA_wx6P2RuM_2kyQg',
    appId: '1:261848373856:android:94b0bf0b071eb7e795c105',
    messagingSenderId: '261848373856',
    projectId: 'raceapp-d75e0',
    databaseURL: 'https://raceapp-d75e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raceapp-d75e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_WSSeLGUQzLrf2pdvB_Z4fyMjcdOmoi8',
    appId: '1:261848373856:ios:346188dba2c6d5ce95c105',
    messagingSenderId: '261848373856',
    projectId: 'raceapp-d75e0',
    databaseURL: 'https://raceapp-d75e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raceapp-d75e0.firebasestorage.app',
    iosBundleId: 'com.example.raceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_WSSeLGUQzLrf2pdvB_Z4fyMjcdOmoi8',
    appId: '1:261848373856:ios:346188dba2c6d5ce95c105',
    messagingSenderId: '261848373856',
    projectId: 'raceapp-d75e0',
    databaseURL: 'https://raceapp-d75e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raceapp-d75e0.firebasestorage.app',
    iosBundleId: 'com.example.raceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRF3CHZ11M6hec1T0Jcs_JO8zpI9z3dIY',
    appId: '1:261848373856:web:163d34f4523abd7395c105',
    messagingSenderId: '261848373856',
    projectId: 'raceapp-d75e0',
    authDomain: 'raceapp-d75e0.firebaseapp.com',
    databaseURL: 'https://raceapp-d75e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'raceapp-d75e0.firebasestorage.app',
    measurementId: 'G-3KEGC99YFG',
  );

}